name: Benchmarks

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.x'
      - name: Install dependencies
        run: go get .
      - name: Run benchmarks
        run: |
          go run . -test.benchtime=1s
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Python dependencies
        run: |
          pip install numpy pandas matplotlib
      - name: Plot results
        run: |
          python plot/plot.py
      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results
