name: Benchmarks

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  benchmarks_fast_1:
    name: Fast benchmarks 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go
      - name: Run benchmarks
        run: |
          go run . -test.benchtime=1s -count=3 \
              query2comp \
              query32arch \
              query256arch \

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: results_fast_1
          path: results/*
          
  benchmarks_fast_2:
    name: Fast benchmarks 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go
      - name: Run benchmarks
        run: |
          go run . -test.benchtime=1s -count=3 \
              random \
              add_remove \
              add_remove_large \
              new_world

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: results_fast_2
          path: results/*

  benchmarks_slow_1:
    name: Slow benchmarks 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go
      - name: Run benchmarks
        run: |
          go run . -test.benchtime=0.1s \
              create2comp \
              create2comp_alloc \
              create10comp \

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: results_slow_1
          path: results/*
          
  benchmarks_slow_2:
    name: Slow benchmarks 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go
      - name: Run benchmarks
        run: |
          go run . -test.benchtime=0.1s \
              delete2comp \
              delete10comp \

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: results_slow_2
          path: results/*
          
  plots:
    name: Plot benchmarks
    runs-on: ubuntu-latest
    needs:
      - benchmarks_fast_1
      - benchmarks_fast_2
      - benchmarks_slow_1
      - benchmarks_slow_2
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Install Python dependencies
        run: |
          pip install -r ./plot/requirements.txt

      - name: Download results_fast_1
        uses: actions/download-artifact@v4
        with:
          name: results_fast_1
          path: results
      - name: Download results_fast_2
        uses: actions/download-artifact@v4
        with:
          name: results_fast_2
          path: results
      - name: Download results_slow_1
        uses: actions/download-artifact@v4
        with:
          name: results_slow_1
          path: results
      - name: Download results_slow_2
        uses: actions/download-artifact@v4
        with:
          name: results_slow_2
          path: results

      - name: Plot results
        run: |
          python plot/plot.py
      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results
