name: Benchmarks

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  benchmarks_fast:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go
      - name: Run benchmarks
        run: |
          go run . -test.benchtime=0.5s \
              query2comp \
              query1in10 \
              query32arch \
              random \
              add_remove \
              add_remove_large \
              new_world

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: results_fast
          path: results/*

  benchmarks_slow:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go
      - name: Run benchmarks
        run: |
          go run . -test.benchtime=0.25s \
              create2comp \
              create2comp_alloc \
              create10comp \
              delete2comp \
              delete10comp \

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: results_slow
          path: results/*
          
  plots:
    name: Plot benchmarks
    runs-on: ubuntu-latest
    needs:
      - benchmarks_fast
      - benchmarks_slow
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Install Python dependencies
        run: |
          pip install -r ./plot/requirements.txt

      - name: Download results_fast
        uses: actions/download-artifact@v4
        with:
          name: results_fast
          path: results
      - name: Download results_slow
        uses: actions/download-artifact@v4
        with:
          name: results_slow
          path: results

      - name: Plot results
        run: |
          python plot/plot.py
      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results
