name: Benchmarks

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go
      - name: Run benchmarks
        run: |
          go run . -test.benchtime=0.25s
      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results
          
  plots:
    name: Plot benchmarks
    runs-on: ubuntu-latest
    needs: benchmarks
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Install Python dependencies
        run: |
          pip install -r ./plot/requirements.txt
      - name: Download results
        uses: actions/download-artifact@v4
        with:
          name: results
          path: .
      - name: Plot results
        run: |
          python plot/plot.py
      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results
